export const destinations = [
    {
        id: "swiss-alps",
        name: "Swiss Alps Expedition",
        description: "Experience the majestic peaks and serene lakes of Switzerland. A 7-day journey through the heart of the Alps.",
        price: "₹85,000",
        image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99",
        rating: 4.9,
        duration: "7 Days",
        lat: 46.5601,
        lng: 8.0160,
        category: "International",
        amenities: ["Wifi", "Pool", "Spa", "Breakfast"],
        hotelType: "Luxury",
        stops: "1 Stop"
    },
    {
        id: "kyoto-culture",
        name: "Kyoto Cultural Journey",
        description: "Immerse yourself in ancient traditions, tea ceremonies, and cherry blossoms in Japan's cultural capital.",
        price: "₹1,20,000",
        image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e",
        rating: 4.8,
        duration: "10 Days",
        lat: 35.0116,
        lng: 135.7681,
        category: "International",
        amenities: ["Wifi", "Guide", "Breakfast"],
        hotelType: "Boutique",
        stops: "Non-stop"
    },
    {
        id: "santorini-sunset",
        name: "Santorini Sunset Bliss",
        description: "Relax in white-washed villas overlooking the deep blue Aegean Sea. The ultimate romantic getaway.",
        price: "₹95,000",
        image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff",
        rating: 4.9,
        duration: "5 Days",
        lat: 36.3932,
        lng: 25.4615,
        category: "International",
        amenities: ["Pool", "Bar", "Ocean View", "Wifi"],
        hotelType: "Resort",
        stops: "1 Stop"
    },
    {
        id: "kerala-backwaters",
        name: "Kerala Backwaters",
        description: "Glide through the palm-fringed canals of God's Own Country in a traditional houseboat.",
        price: "₹35,000",
        image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944",
        rating: 4.7,
        duration: "4 Days",
        lat: 9.9312,
        lng: 76.2673,
        category: "Domestic",
        amenities: ["Meals", "Guide", "Boat"],
        hotelType: "Homestay",
        stops: "Non-stop"
    },
    {
        id: "ladakh-adventure",
        name: "Ladakh Adventure",
        description: "Explore the stark beauty of the Himalayas, high mountain passes, and Buddhist monasteries.",
        price: "₹45,000",
        image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2",
        rating: 4.8,
        duration: "6 Days",
        lat: 34.1526,
        lng: 77.5770,
        category: "Domestic",
        amenities: ["Oxygen", "Meals", "Guide", "Bonfire"],
        hotelType: "Boutique",
        stops: "Non-stop"
    },
    {
        id: "rajasthan-royals",
        name: "Royal Rajasthan",
        description: "Live like a Maharaja. Visit the palaces of Jaipur, Udaipur, and Jodhpur.",
        price: "₹55,000",
        image: "https://images.unsplash.com/photo-1477587458883-47145ed94245",
        rating: 4.9,
        duration: "8 Days",
        lat: 26.9124,
        lng: 75.7873,
        category: "Domestic",
        amenities: ["Pool", "Spa", "Heritage Walk", "Breakfast"],
        hotelType: "Luxury",
        stops: "Non-stop"
    }
];
