services:
  - type: web
    name: travel-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: 20.9.0
